name: Validate SSH keys

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.ssh/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check if keys in .ssh directory are valid
        run: find .ssh -type f -exec ssh-keygen -lf {} \;