name: Validate SSH keys

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.ssh/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: all files in .ssh directory must be valid ssh public keys
        run: find .ssh -type f -exec ssh-keygen -lf {} \;

      - name: each file in .ssh must be in a dedicated catalog
        run: |
          [ $(find .ssh -maxdepth 1 -type f | wc -l) -eq 0 ]